import React from "react";
import "./HomePage.css";
import HomeImage from "../../assets/86bf65c7-2c64-4b5e-9391-da612b8b1a58.jpg";
import CourseComponent from "../../components/CourseComponent/CourseComponent";
import INSTAGRAM from "../../assets/4d3e5e95-7e4f-4d7b-a8de-66b9f5c4213a.jpg";
import FACEBOOK from "../../assets/72fad130-a079-451f-95c6-15c1c3a65c8a.jpg";

function HomePage() {
  return (
    <div className="home-page-container">
      <section className="top-section">
        <img className="top-section-image" src={HomeImage} alt="" />
        <h1 className="top-section-text">Welcome to 4Finance...</h1>
      </section>

      <div className="home-page-content">
        {/* About Us Section */}
        <section className="about-us-section">
          <h3 className="titles">About Us</h3>
          <p className="about-us-section-text">
            4finance operates a portfolio of market-leading brands offering
            simple, useful and transparent products to millions of customers. We
            provide convenient products in a responsible way to the many
            consumers who are often undeserved by conventional providers. Small
            and Medium Enterprises (SMEs) play a major role in most economies,
            particularly in developing countries. SMEs account for the majority
            of businesses worldwide and are important contributors to job
            creation and global economic development. They represent about 90%
            of businesses and more than 50% of employment worldwide. Formal SMEs
            contribute up to 40% of national income (GDP) in emerging economies.
            These numbers are significantly higher when informal SMEs are
            included. According to our estimates, 600 million jobs will be
            needed by 2030 to absorb the growing global workforce, which makes
            SME development a high priority for many governments around the
            world. In emerging markets, most formal jobs are generated by SMEs,
            which create 7 out of 10 jobs. However, access to finance is a key
            constraint to SME growth, it is the second most cited obstacle
            facing SMEs to grow their businesses in emerging markets and
            developing countries. SMEs are less likely to be able to obtain bank
            loans than large firms; instead, they rely on internal funds, or
            cash from friends and family, to launch and initially run their
            enterprises. The International Finance Corporation (IFC) estimates
            that 65 million firms, or 40% of formal micro, small and medium
            enterprises (Mses) in developing countries, have an unmet financing
            need of $5.2 trillion every year, which is equivalent to 1.4 times
            the current level of the global MSME lending. East Asia And Pacific
            accounts for the largest share (46%) of the total global finance gap
            and is followed by Latin America and the Caribbean (23%) and Europe
            and Central Asia (15%). The gap volume varies considerably region to
            region. Latin America and the Caribbean and the Middle East and
            North Africa regions, in particular, have the highest proportion of
            the finance gap compared to potential demand, measured at 87% and
            88%, respectively. About half of formal SMEs don’t have access to
            formal credit. The financing gap is even larger when micro and
            informal enterprises are taken into account.
          </p>
        </section>

        {/* Courses Section */}
        <section className="courses-section">
          <h2 className="titles">Courses</h2>
          <div className="courses-list">
            <CourseComponent
              name="React.js"
              description="React is one of the most popular frontend libraries React.ls, to build interactive UI, integrated with one of the best state management tools 'Redux'."
              creditNumber={3}
            />
            <CourseComponent
              name="API.NET Core Web API"
              description="API is the acronym for Application Programming Interface, which is a software intermediary that allows two applications to talk to each other. Each time you use an app like Facebook, send an instant message, or check the weather on your phone, you are using an API."
              creditNumber={3}
            />
            <CourseComponent
              name="MySQL"
              description="SQL is used to communicate with a database. According to ANSI (American National Standards Institute), it is the standard language for relational database management systems. SQL statements are used to perform tasks such as update data on a database, or retrieve data from a database."
              creditNumber={3}
            />
          </div>
        </section>

        {/* Contact Us Section */}
        <section className="contact-us-section">
          <h2 className="titles">Contact Us</h2>
          <div className="contact-us-social-media-container">
            <div>
              <h3>
                Phone Number: <a href="tel:+961 81 746 018"> +961 81 746 018</a>
              </h3>
              <h3>
                Email:{" "}
                <a href="mailto:nibal358164@gmail.com">nibal358164@gmail.com</a>
              </h3>
            </div>

            <div className="both-instagram-facebook">
              <a href="https://instagram.com/4_finance_?igshid=YmMyMTA2M2Y=">
                <img className="instagram-fb" src={INSTAGRAM} alt="instagram" />
              </a>
              <a href="https://www.facebook.com/HB4Finance?mibextid=ZbWKwL">
                <img className="instagram-fb" src={FACEBOOK} alt="facebook" />
              </a>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}

export default HomePage;
