// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SoapLush.Data;

#nullable disable

namespace SoapLush.Migrations
{
    [DbContext(typeof(SoapLushDbContext))]
    [Migration("20230102155419_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SoapCategorySoapSubCategory", b =>
                {
                    b.Property<int>("SoapSubCategoriesid")
                        .HasColumnType("int");

                    b.Property<int>("soapCategoriesid")
                        .HasColumnType("int");

                    b.HasKey("SoapSubCategoriesid", "soapCategoriesid");

                    b.HasIndex("soapCategoriesid");

                    b.ToTable("SoapCategorySoapSubCategory");
                });

            modelBuilder.Entity("SoapLush.Models.Products", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SoapCategoryid")
                        .HasColumnType("int");

                    b.Property<string>("subCategortyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("SoapCategoryid");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SoapLush.Models.SoapCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("subCategortyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SoapCategories");
                });

            modelBuilder.Entity("SoapLush.Models.SoapSubCategory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("SoapSubCategories");
                });

            modelBuilder.Entity("SoapCategorySoapSubCategory", b =>
                {
                    b.HasOne("SoapLush.Models.SoapSubCategory", null)
                        .WithMany()
                        .HasForeignKey("SoapSubCategoriesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoapLush.Models.SoapCategory", null)
                        .WithMany()
                        .HasForeignKey("soapCategoriesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SoapLush.Models.Products", b =>
                {
                    b.HasOne("SoapLush.Models.SoapCategory", null)
                        .WithMany("Products")
                        .HasForeignKey("SoapCategoryid");
                });

            modelBuilder.Entity("SoapLush.Models.SoapCategory", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
